name: nursing_request
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  mongo_dart: ^0.10.3
  ios_utsname_ext: ^2.3.0
  android_id: ^0.4.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/nurse.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/nurse.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/nurse.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/nurse.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
  fonts:
    - family: SukhumvitSet
      fonts:
        - asset: assets/fonts/SukhumvitSet/SukhumvitSet-Medium.ttf
          weight: 500
        - asset: assets/fonts/SukhumvitSet/SukhumvitSet-SemiBold.ttf
          weight: 800
  
